name: nvim-snap

on:
  push:
  pull_request:

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
      - name: Check version of Neovim
        run: nvim --version
      - name: Install nvim-snap
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download -R kyoh86/nvim-snap -p "nvim-snap_*_linux_amd64.tar.gz" -O /tmp/nvim-snap.tar.gz
          tar -xzf /tmp/nvim-snap.tar.gz -C /tmp
          install /tmp/nvim-snap /usr/local/bin/nvim-snap
      - name: Report snapshots
        run: |
          export XDG_RUNTIME_DIR=/tmp/xdg-runtime
          mkdir -p "$XDG_RUNTIME_DIR"
          chmod 700 "$XDG_RUNTIME_DIR"
          nvim-snap report --root . --cases-dir snapcase --output diff --diff-format text --diff-always
      - name: Upload diffs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nvim-snap-diff
          path: |
            .nvim-snap-diff/*
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nvim-snap-log
          path: |
            **/.nvimlog
          include-hidden-files: true
